import { ServiceProvidersMap } from "@type/app";

const serviceProvidersMap: ServiceProvidersMap = {
  internet: {
    mtn: {
      id: 1,
      serviceId: "mtn",
      name: "MTN",
      logo: require("@assets/images/services/mtn.png"),
      type: ["VTU"],
    },
    glo: {
      serviceId: "glo",
      name: "GLO",
      logo: require("@assets/images/services/glo.png"),
      id: 2,
      type: ["VTU"],
    },
    "9mobile": {
      id: 3,
      serviceId: "9mobile",
      name: "9Mobile",
      logo: require("@assets/images/services/nine-mobile.png"),
      type: ["VTU"],
    },
    airtel: {
      id: 4,
      serviceId: "airtel",
      name: "Airtel",
      logo: require("@assets/images/services/airtel.png"),
      type: ["VTU"],
    },
  },
  education: {
    jamb: {
      id: 1,
      serviceId: "jamb",
      name: "Jamb",
      description: "Joint Admission and Matriculation Board",
      logo: require("@assets/images/services/jamb.png"),
    },
    ibbu: {
      id: 2,
      serviceId: "ibbu",
      name: "IBBU",
      description: "Institute of Management Technology",
      logo: require("@assets/images/services/ibbu.png"),
    },
    asam: {
      id: 2,
      serviceId: "asam",
      name: "ASAM",
      description: "Association of Medical Lab. Scientists",
      logo: require("@assets/images/services/asam.png"),
    },
  },
  entertainment: {
    gotv: {
      id: 2,
      name: "Gotv",
      serviceId: "gotv",
      logo: require("@assets/images/services/gotv.png"),
    },
    dstv: {
      id: 2,
      name: "Dstv",
      serviceId: "dstv",
      logo: require("@assets/images/services/dstv.png"),
    },
    startime: {
      id: 2,
      name: "Startime",
      serviceId: "startime",
      logo: require("@assets/images/services/startimes.png"),
    },
  },
  electricity: {
    ikedc: {
      id: 1,
      name: "Ikeja Electric Distribution Company (IKEDC)",
      serviceId: "ikedc",
      logo: require("@assets/images/services/ikedc.png"),
    },
    ekedc: {
      id: 2,
      name: "Eko Electricity Distribution Company (EKEDC)",
      serviceId: "ekedc",
      logo: require("@assets/images/services/ekedc.png"),
    },
    aedc: {
      id: 3,
      name: "Abuja Electricity Distribution Company (AEDC)",
      serviceId: "aedc",
      logo: require("@assets/images/services/aedc.png"),
    },
    kedco: {
      id: 4,
      name: "Kano Electricity Distribution Company (KEDCO)",
      serviceId: "kedco",
      logo: require("@assets/images/services/kedco.png"),
    },
    eedc: {
      id: 5,
      name: "Enugu Electricity Distribution Company (EEDC)",
      serviceId: "eedc",
      logo: require("@assets/images/services/eedc.png"),
    },
    phedc: {
      id: 6,
      name: "Port Harcourt Electricity Distribution Company (PHED)",
      serviceId: "phedc",
      logo: require("@assets/images/services/phed.png"),
    },
    ibedc: {
      id: 7,
      name: "Ibadan Electricity Distribution Company (IBEDC)",
      serviceId: "ibedc",
      logo: require("@assets/images/services/ibedc.png"),
    },
    kaedco: {
      id: 8,
      name: "Kaduna Electric Distribution Company (KAEDC)",
      serviceId: "kaedco",
      logo: require("@assets/images/services/kaedco.png"),
    },
    jedc: {
      id: 9,
      name: "Jos Electricity Distribution Company (JEDC)",
      serviceId: "jedc",
      logo: require("@assets/images/services/jed.png"),
    },
    bedc: {
      id: 10,
      name: "Benin Electricity Distribution Company (BEDC)",
      serviceId: "bedc",
      logo: require("@assets/images/services/bedc.png"),
    },
    yedc: {
      id: 11,
      name: "Yola Electricity Distribution Company (YEDC)",
      serviceId: "yedc",
      logo: require("@assets/images/services/yedc.png"),
    },
    abedc: {
      id: 12,
      name: "Aba Electricity Distribution Company (ABEDC)",
      serviceId: "abedc",
      logo: require("@assets/images/services/abed.png"),
    },
  },
};

const INTERNET_PROVIDERS = ["mtn", "airtel", "9mobile", "glo"] as const;

const providerNumberCodes = {
  "0701": { network: "Airtel Nigeria", provider: "Airtel" },
  "07020": { network: "Smile", provider: "Smile" },
  "07025": { network: "MTN Nigeria (formerly Visafone)", provider: "MTN" },
  "07026": { network: "MTN Nigeria (formerly Visafone)", provider: "MTN" },
  "07027": { network: "Multi-Links", provider: "Multi-Links" },
  "07028": { network: "Starcomms", provider: "Starcomms" },
  "07029": { network: "Starcomms", provider: "Starcomms" },
  "0703": { network: "MTN Nigeria", provider: "MTN" },
  "0704": { network: "MTN Nigeria (formerly Visafone)", provider: "MTN" },
  "0705": { network: "Globacom", provider: "Glo" },
  "0706": { network: "MTN Nigeria", provider: "MTN" },
  "0707": { network: "MTN Nigeria (formerly ZoomMobile)", provider: "MTN" },
  "0708": { network: "Airtel Nigeria", provider: "Airtel" },
  "0709": { network: "Multi-Links", provider: "Multi-Links" },
  "0802": { network: "Airtel Nigeria", provider: "Airtel" },
  "0803": { network: "MTN Nigeria", provider: "MTN" },
  "0804": { network: "Mtel", provider: "Mtel" },
  "0805": { network: "Globacom", provider: "Glo" },
  "0806": { network: "MTN Nigeria", provider: "MTN" },
  "0807": { network: "Globacom", provider: "Glo" },
  "0808": { network: "Airtel Nigeria", provider: "Airtel" },
  "0809": { network: "9mobile", provider: "9mobile" },
  "0810": { network: "MTN Nigeria", provider: "MTN" },
  "0811": { network: "Globacom", provider: "Glo" },
  "0812": { network: "Airtel Nigeria", provider: "Airtel" },
  "0813": { network: "MTN Nigeria", provider: "MTN" },
  "0814": { network: "MTN Nigeria", provider: "MTN" },
  "0815": { network: "Globacom", provider: "Glo" },
  "0816": { network: "MTN Nigeria", provider: "MTN" },
  "0817": { network: "9mobile", provider: "9mobile" },
  "0818": { network: "9mobile", provider: "9mobile" },
  "0819": { network: "Starcomms", provider: "Starcomms" },
  "0909": { network: "9mobile", provider: "9mobile" },
  "0908": { network: "9mobile", provider: "9mobile" },
  "0901": { network: "Airtel Nigeria", provider: "Airtel" },
  "0902": { network: "Airtel Nigeria", provider: "Airtel" },
  "0903": { network: "MTN Nigeria", provider: "MTN" },
  "0904": { network: "Airtel Nigeria", provider: "Airtel" },
  "0905": { network: "Globacom", provider: "Glo" },
  "0906": { network: "MTN Nigeria", provider: "MTN" },
  "0907": { network: "Airtel Nigeria", provider: "Airtel" },
  "0915": { network: "Globacom", provider: "Glo" },
  "0913": { network: "MTN Nigeria", provider: "MTN" },
  "0912": { network: "Airtel Nigeria", provider: "Airtel" },
  "0916": { network: "MTN Nigeria", provider: "MTN" },
  "0911": { network: "Airtel Nigeria", provider: "Airtel" },
};

const pluralProviderMap = {
  mtn: "an MTN",
  glo: "a Glo",
  airtel: "an Airtel",
  "9mobile": "a 9mobile",
};

export { serviceProvidersMap, INTERNET_PROVIDERS, providerNumberCodes, pluralProviderMap };
