export const SCREENS = {
  HOME: "Home",
  PROFILE: "Profile",
  CHANGE_PASSWORD: "Change Password",
  ADD_MONEY: "Add Money",
  CARD_DETAILS: "Card Details",
  PAYMENT_SUCCESS: "Payment Success",
  AIRTIME_PURCHASE: "Airtime Purchase",
  AIRTIME_EPIN_PURCHASE: "Airtime EPIN Purchase",
  DATA_PURCHASE: "Data Purchase",
  CONFIRM_TRANSACTION: "Confirm Transaction",
  EDUCATION: 'Education',
  SELECT_EDUCATIONAL_PAYMENT: "Select Educational Payment",
  EDUCATIONAL_PAYMENT: "Educational Payment",
  TV_SUBSCRIPTION: "TV Subscription",
  ELECTRICITY_BILL: "Electricity Bill",
  BINAPAY_REWARDS: "BinaPay Rewards",
  EARNING_SUMMARY: "Earning Summary",
  VERIFY_ACCOUNT: "Verify Account",
  ONE_TIME_PASSWORD: "One Time Password",
  FORGOT_PASSWORD: "Forgot Password",
  RESET_PASSWORD: "Reset Password",
  RESET_PASSWORD_SUCCESS: "Reset Password Successful",
  ONBOARDING: "Onboarding",
  AUTH: "Auth",
  BUSY: "Busy",
  SERVICES: "Services",
  LOGIN: "Login",
  REGISTER: "Register",
  NOTIFICATION: "Notification",
  TRANSACTION_HISTORY: "Transaction History",
  REGISTER_SUCCESS: "Register Success",
  VERIFY_EMAIL: "Verify Email",
  COMPLETE_REGISTRATION: "Complete Registration",
  START: "Start",
  SERVICE_PURCHASE_SUCCESS: "Service Purchase Success",
  TRANSACTION_DETAILS: "Transaction Details",
  SETTINGS: "Settings",
  VIEW_NOTIFICATION: "View Notification",
};
